inventory/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^', include('sitio.urls')),
)

sitio/urls.py
from django.conf.urls.defaults import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('sitio.views',
        url(r'^$','index',name='index'),
        url(r'^welcome$','welcome'),
        url(r'^login$','loginusr',name='loginusr'),
        url(r'^logoff$','logoff',name='logoff'),
    )

urlpatterns += patterns('sitio.inventario_views',
        url(r'^addform$','addform',name='addform'),
        url(r'^addhardware$','addhardware',name='addhardware'),
        url(r'^modelos$','modelosXmarca',name='modelosXmarca'),
        url(r'^responsables$','responsables',name='responsables'),
        url(r'^searching$','search_engine',name='search_engine'),
        url(r'^searching/(?P<items_per_page>\d+)/$','search_engine',name='search_engine'),
        url(r'^migrate$','migration',name='migration'),
        url(r'^details$','details',name='details'),
        url(r'^ending/(?P<idu>\d+)/$','ending',name='ending'),
        url(r'^autofill$','autofill',name='autofill'),
        url(r'^deleting_h/(?P<idu>\d+)/$','deleting_h',name='deleting_h'),
        url(r'^log/(?P<idu>\d+)/$','loggl',name='loggl'),
        url(r'^reporter$','reporter',name='reporter'),
    )
urlpatterns += patterns('sitio.user_views',
    url(r'^users/$','index',name='index'),
    url(r'^users/(?P<idu>\d+)/$','index',name='index'),
    url(r'^userform/$','userform',name='userform'),
    url(r'^userform/(?P<idu>\d+)/$','userform',name='userform'),
    url(r'^deluser/(?P<idu>\d+)/$','deluser',name='deluser'),
    url(r'^addinguser$','addinguser',name='addinguser'),
    )

urlpatterns += patterns('sitio.rack_views',
    url(r'^rack_form/$','rack_form',name='rack_form'),
    url(r'^rack_form/(?P<idu>\d+)/$','rack_form',name='rack_form'),
    url(r'^items_in_rack/(?P<idrack>\d+)/$','items_in_rack',name='items_in_rack'),
    )

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitio/models.py
# -*- coding: utf_8 -*-
# -*- encoding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

class Marca(models.Model):
    nombre = models.CharField(u'Marca',max_length=100)

class Modelo(models.Model):
    marca = models.ForeignKey(Marca)
    nombre = models.CharField(u'Marca',max_length=100)

class Tipo_hdwre(models.Model):
    nombre = models.CharField('',max_length=100)

class Hardware(models.Model):
    idocs = models.IntegerField(u'Clave OSC Inventory',blank=True,null=True)
    nombre = models.CharField(u'Nombre Hardware',max_length=150,null=True,blank=True)
    cluster = models.CharField(u'Cluster',max_length=50,blank=True,null=True)
    ssn = models.CharField(u'Numero de serie',max_length=150,null=True,blank=True)
    marca = models.ForeignKey(Marca,blank=True,null=True)
    modelo = models.ForeignKey(Modelo,blank=True,null=True)
    posicion = models.CharField(u'Posicion',max_length=100,blank=True,null=True)
    ambiente = models.CharField(u'Ambiente',max_length=150,blank=True,null=True)
    lun = models.CharField(u'Lun',max_length=100,blank=True,null=True)
    consola = models.CharField(u'Consola',max_length=50,blank=True,null=True)
    num_activo = models.CharField(u'Nm. Activo',max_length=120,blank=True,null=True)
    cmdb = models.BooleanField(u'CMDB',default=True)
    tipo_hdwre = models.CharField(u'Tipo de Hardware',max_length=120,blank=True,null=True)
    #  define el status del registro {1:activo,2:eliminado,3:edicion,4:ocs}
    db_state = models.IntegerField(u'Status',default=3,blank=True,null=True)
    fecha_registro = models.DateField(u'Fecha Registro',auto_now=True)
    fecha_llegada = models.DateField(u'fecha llegada',blank=True,null=True)
    fecha_instalacion = models.DateField(u'fecha instalacion',blank=True,null=True)
    fecha_apagado = models.DateField(u'fecha apagado',blank=True,null=True)


class Disco(models.Model):
    hardware=models.ForeignKey(Hardware)
    id_charola = models.CharField('',max_length=20,blank=True,null=True)
    tipo_disco = models.CharField('',max_length=100,blank=True,null=True)
    discos = models.CharField('',max_length=100,blank=True,null=True)
    espacio_ocupado = models.CharField('',max_length=100,blank=True,null=True)
    tamanyo_disco = models.CharField('',max_length=20,blank=True,null=True)

class Ips(models.Model):
    hardware = models.ForeignKey(Hardware)
    ipnum = models.CharField('',max_length=150,blank=True,null=True)
    nameip = models.CharField('',max_length=150,blank=True,null=True)
    descrip = models.CharField('',max_length=150,blank=True,null=True)

class Netcard(models.Model):
    hardware = models.ForeignKey(Hardware)
    cardname = models.CharField('',max_length=120,blank=True,null=True)
    speedcard = models.CharField('',max_length=120,blank=True,null=True)

class Network(models.Model):
    hardware = models.ForeignKey(Hardware)
    #cluster = models.CharField('',max_length=50,blank=True,null=True)
    puertos_total = models.IntegerField(u'Puertos Totales',blank=True,null=True)
    puertos_licenciados = models.IntegerField(u'Puertos Licenciados',blank=True,null=True)
    puertos_usados = models.TextField(u'Puertos Usados',blank=True,null=True)
    puerto_switch = models.IntegerField(u'Puerto Switch',blank=True,null=True)
    respaldos = models.CharField(u'Respaldos',max_length=250,blank=True,null=True)
    monitores = models.CharField(u'Monitores',max_length=250,blank=True,null=True)
    no_serie_oa = models.CharField(u'Nmero de serie OA',max_length=100,blank=True,null=True)
    
class Features(models.Model):
    hardware = models.ForeignKey(Hardware)
    ram = models.CharField(u'Memoria Ram',max_length=150,blank=True,null=True)
    espacio_asignado = models.TextField(u'Espacio Asignado',blank=True,null=True)
    antivirus = models.CharField('',max_length=150,blank=True,null=True)
    delegado_prod = models.CharField(u'Delegado Prod',max_length=150,blank=True,null=True)
    #    INFO DE PROCESADORES
    proc_socket = models.CharField(u'Socket Procesador',max_length=150,blank=True,null=True)
    proc_cores = models.CharField(u'Cores',max_length=150,blank=True,null=True)
    proc_arq = models.CharField(u'Arquitectura Procesador',max_length=150,blank=True,null=True)

class Empresa(models.Model):
    empresa = models.CharField('',max_length=150)

class Responsable(models.Model):
    responsable = models.CharField('',max_length=220)
    empresa = models.ForeignKey(Empresa)

class Responsable_garantia(models.Model):
    hardware = models.ForeignKey(Hardware)
    nombre_aplicacion = models.CharField(u'Nombre de la aplicacion',max_length=150,blank=True,null=True)
    responsable = models.ForeignKey(Responsable,blank=True,null=True)
    area = models.CharField('Area',max_length=120,blank=True,null=True)
    empresa = models.ForeignKey(Empresa,blank=True,null=True)
    tipo_soporte = models.CharField(u'Tipo de Soporte',max_length=250,blank=True,null=True)
    fecha_inicio = models.DateField(u'Fecha Inicio',blank=True,null=True)
    fecha_fin = models.DateField(u'Fecha Fin',blank=True,null=True)

#LUGARES
class Edificio(models.Model):
    nombre_edificio = models.CharField('',max_length=100)
    def racks(self):
        rs = self.lugar_set.values('num_rack').distinct()
        return rs


class Lugar(models.Model):
    hardware = models.ForeignKey(Hardware,blank=True,null=True)
    edificio = models.ForeignKey(Edificio,blank=True,null=True)
    num_rack = models.CharField(u'Numero de Rack',max_length=50,blank=True,null=True)
    fila_rack = models.CharField(u'Fila Rack',max_length=50,blank=True,null=True)
    unidades = models.CharField(u'Us',max_length=20,blank=True,null=True)
    posicion_enclousure = models.CharField(u'Posicion Enclousure',max_length=150,blank=True,null=True)
    formato_nombre = models.CharField(u'Formato',max_length=150,blank=True,null=True)
    no_enclousure = models.CharField(u'Enclousure',max_length=100,blank=True,null=True)


class Software(models.Model):
    hardware = models.ForeignKey(Hardware)
    plataforma = models.CharField(u'Sistema Operativo',max_length=150,blank=True,null=True)
    version = models.CharField(u'Version',max_length=150,blank=True,null=True)
    release = models.TextField(u'Realease',blank=True,null=True)
    service_pack = models.CharField(u'Service Pack',max_length=100,default=False,blank=True,null=True)


class SearchEngine(models.Model):
    hardware = models.ForeignKey(Hardware)
    texto = models.TextField('')


class Log(models.Model):
    user = models.ForeignKey(User)
    datemodifier = models.DateField(auto_now=True)
    hardware = models.ForeignKey(Hardware,null=True,blank=True)
    before = models.TextField()
    after = models.TextField()


class Rack(models.Model):
    edificio = models.ForeignKey(Edificio)
    uds = models.IntegerField('')
    marck_rack = models.CharField('',max_length=100,blank=True,null=True)
    distribution = models.TextField('')
    configuration = models.TextField('')
    marca = models.ForeignKey(Marca)
    modelo = models.ForeignKey(Modelo)
    desc = models.TextField('')

sitio/views.py
# -*- encoding: utf-8 -*-
from django.http import HttpResponse
from django.template.loader import get_template
from django.template import Context
from django.shortcuts import get_object_or_404, render_to_response
from django.shortcuts import redirect
from django.template.context import RequestContext
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required, permission_required
import simplejson
from sitio.auth import AuthManager
from sitio.models import * 
from django.db import models
from django.db.models import Q


def index(request):
    context = RequestContext(request)
    user = request.user
    if user.is_active:
        return redirect('/welcome')
    return render_to_response("inicio.html",
                              {'usr':user},
                              context)

def logoff(request):
    logout(request)
    return redirect('/')

@login_required(login_url="/")
def welcome(request):
    fieldsch = {}
    modelos = (Hardware,Network,Features,Responsable_garantia,Software)
    compuestos = {}
    for m in modelos:
        campos = m._meta.fields
        for c in campos:
            if str(c.get_internal_type())=='CharField' and c.name!='antivirus':
                if str(m.__name__).lower()!='hardware':
                    fieldsch[c.name]={'model':str(m.__name__).lower(),
                                  'field':str(c.name),
                                  'verbose_name':str(c.verbose_name)        
                    }
                else:
                    fieldsch[c.name]={'model':'',
                                      'field':str(c.name),
                                      'verbose_name':str(c.verbose_name) 
                    }
    context = RequestContext(request)
    user = request.user
    marca = Marca.objects.all()
    grupos = [(x.name) for x in request.user.groups.all()]

    args = {}

    relationist = {'linux':{'software__plataforma__icontains':'linux'},
                   'as400':{'tipo_hdwre__icontains':'as400'},
                   'almacenamiento':{'tipo_hdwre__icontains':'vtl'},
                   'windows':{'software__plataforma__icontains':'windows'},
                   'admin':'',
                    }

    total = Hardware.objects.all()

    virtual = len(total.filter(tipo_hdwre__icontains='virtual'))
    fisico = len(total.filter(tipo_hdwre__icontains='fisico'))
    otros = len(total.filter(~Q(tipo_hdwre__icontains='fisico') & ~Q(tipo_hdwre__icontains='virtual') ))
    how_often = len(Hardware.objects.filter(**args))

    states = {'virtual':virtual,'total':len(total),'fisico':fisico,'otros':otros}

    FECHAS = (
            ('fecha_registro',u'Fecha de registro')
            ,('hardware__fecha_llegada',u'Fecha llegada'),
            ('fecha_instalacion',u'Fecha Instalación'),
            ('fecha_apagado','Fecha apagado'),
            ('responsable_garantia__fecha_inicio',u'Fecha inicio de garantía'),
            ('responsable_garantia__fecha_fin',u'Fecha fin de garantina'),
            )
    
    return render_to_response("welcome.html",
                              {'usr':user,
                               'marca':marca,
                               'gp':grupos,
                               'how_often':how_often,
                               'fechas':FECHAS,
                               'reports':states,
                                'fields':fieldsch},
                              context)

'''
    WEBSERVICE PARA AUTENTICAR AL USUARIO
    RETORNA UN JSON CON LA RESPUESTA
'''
def loginusr(request):
    usrchek = AuthManager(request)
    check = usrchek.is_pathient()
    
    if check:
        if check.is_active:
            login(request,check)
            response = {'ok':True}
        else:
            response = {'ok':'NOT ACTIVE'}
    else:
        response= {'ok':False}
    response = simplejson.dumps(response)
    return HttpResponse(response)

    context = RequestContext(request)
    user = request.user
    return render_to_response("inicio.html",
                              {'usr':user},
                              context)

sitio/templates/pices/details/features.html
<div>
    <label for="ram">RAM</label>
    <span class="inline_blocke values_info">{{values.features_set.all.0.ram}}</span>
</div>            
<div>
    <label for="espacio_asignado">Espacio asignado</label>
    <span class="inline_blocke values_info">{{values.features_set.all.0.espacio_asignado}}</span>
</div>            
<div>
    <label for="antivirus">Antivirus</label>
    <span class="inline_blocke values_info">{{values.features_set.all.0.antivirus}}</span>
</div>            
<div>
    <label for="delegado_prod">Delegado Prod</label>
    <span class="inline_blocke values_info">{{values.features_set.all.0.delegado_prod}}</span>
</div>            
<div>
    <label for="proc_socket">Socket Procesador</label>
    <span class="inline_blocke values_info">{{values.features_set.all.0.proc_socket}}</span>
</div>            
<div>
    <label for="proc_cores">CORES</label>
    <span class="inline_blocke values_info">{{values.features_set.all.0.proc_cores}}</span>
</div>            
<div>
    <label for="posicion_enclousure">Posición Enclousure</label>
    <span class="inline_blocke values_info">{{values.features_set.all.0.posicion_enclousure}}</span>
</div>            
<div>
    <label for="proc_arq">ARQ Procesador</label>
    <span class="inline_blocke values_info">{{values.features_set.all.0.proc_arq}}</span>
</div>            
<div>
    <label for="formato_nombre">Formato</label>
    <span class="inline_blocke values_info">{{values.features_set.all.0.formato_nombre}}</span>
</div>

<div id="block_caja_discos">
    <h3>CHAROLA DE DISCOS</h3>
    {% if values.disco_set.all %}
       {% for d in values.disco_set.all %}
            <div class="disc_info">
                 <label>ID Charola</label>
                 <span class="inline_blocke values_info">{{d.id_charola}}</span>
                 <label>Espacio Discos </label>
                 <span class="inline_blocke values_info">{{d.discos}}</span>
                 <label>Espacio Ocupado</label>
                 <span class="inline_blocke values_info">{{d.espacio_ocupado}}</span>
                 <label>Tipo Disco</label>
                 <span class="inline_blocke values_info">{{d.tipo_disco}}</span>
                 <label>Tamaño Discos</label>
                 <span class="inline_blocke values_info">{{d.tamanyo_disco}}</span>
             </div>
        {% endfor %}
    {% endif%}
</div>

sitio/templates/pices/details/infogeneral.html
<div>
    <label for="tipo_hdwre">Tipo Hardware</label>
    <span class="inline_blocke values_info">{{values.tipo_hdwre}}</span>
</div>

<div>
    <input type="hidden" name="idocs" id="idocs" value="" />
    <label for="nombre">Nombre</label>
    <span id="nombre" class="inline_blocke values_info">{{values.nombre}}</span>
</div>
<div>
    <label for="ssn">SSN</label>
    <span id="ssn" class="inline_blocke values_info">{{values.ssn}}</span>
</div>
<div>
    <label for="marca">Marca</label>
    <span id="marca" class="inline_blocke values_info">{{values.marca.nombre}}</span>
</div>
<div>
    <label for="modelo">Modelo</label>
    <span id="modelo" class="inline_blocke values_info">{{values.modelo.nombre}}</span>
</div>
<div>
    <label for="consola">Consola</label>
    <span id="consola" class="inline_blocke values_info">{{values.consola}}</span>
</div>

<div>
    <label for="ambiente">Entorno</label>
    <span id="ambinete" class="inline_blocke values_info">{{values.ambiente}}</span>
</div>
<div>
    <label for="posicion">Posición</label>
    <span id="posicion" class="inline_blocke values_info">{{values.posicion}}</span>
</div>

<div>
    <label for="lun">Lun</label>
    <span id="lun" class="inline_blocke values_info">{{values.lun}}</span>
</div>

<div>
    <label for="cmdb">CMDB</label>
    <span id="cmdb" class="inline_blocke values_info">{{values.cmdb}}</span>
</div>

sitio/templates/pices/details/location.html
<div>
    <label for="edificio">Edificio</label>
    <span id="edificio" class="inline_blocke values_info">{{values.lugar_set.all.0.edificio.nombre}}</span>
</div>

<div>
    <label for="num_rack">Rack</label>
    <span id="num_rack" class="inline_blocke values_info">{{values.lugar_set.all.0.num_rack}}</span>
</div>

<div>
    <label for="formato_nombre">Formato</label>
    <span id="formato_nombre" class="inline_blocke values_info">{{values.lugar_set.all.0.formato_nombre}}</span>
</div>   

<div>
    <label for="unidades">Unidades</label>
    <span id="unidades" class="inline_blocke values_info">{{values.lugar_set.all.0.unidades}}</span>
</div>

<div>
    <label for="fila_rack">Fila</label>
    <span id="fila_rack" class="inline_blocke values_info">{{values.lugar_set.all.0.fila_rack}}</span>
</div>

sitio/templates/pices/details/log.html
<div id="form_dentro" class="formface logg">
    {% if response %}

    <ul>
        {% for c in cambios %}
        <li>{{c.cuando}} -- {{c.quien}}
            <div>
                <ul class="inline_blocke">
                    <li>ANTES</li>
                    {% for x,y in c.antes.items %}
                        <li>{{x}}:{{y}}</li>
                    {% endfor %}
                </ul>
                <ul class="inline_blocke">
                    <li>AHORA</li>
                    {% for x,y in c.ahora.items %}
                        <li>{{x}} : {{y}}</li>
                    {% endfor %}
                </ul>
            </div>
        </li>
        {% endfor %}
    </ul>
    {%else%}
        <div class="buton_standart">No se han registrado cambios en este registro.</div>
    {%endif%}
</div>

sitio/templates/pices/details/network.html
<div>
    <label for="ip">IP's</label>


    <span id="ip" class="inline_blocke values_info">{{values.network_set.all.0.ip|linebreaks}}</span>
{% for ipp in values.ips_set.all %}
   <div class="ip_info">
        <div class="inline_blocke" style="width:120px;"><span>NOMBRE:</span><br/>{{ipp.nameip}}</div>
        <div class="inline_blocke" style="width:150px;"><span>NUM:</span><br/>{{ipp.ipnum}}</div>
        <div class="inline_blocke" style="width:150px;"><span>DESC:</span><br/> {{ipp.descrip}}</div>
   </div>
{% endfor %}

</div>            
<div>
    <label for="puertos_total">Puertos total</label>
    <span id="puertos_total" class="inline_blocke values_info">{{values.network_set.all.0.puertos_total}}</span>
</div>
<div>
    <label for="puertos_licenciados">Puertos licenciados</label>
    <span id="puertos_licenciados" class="inline_blocke values_info">{{values.network_set.all.0.puertos_licenciados}}</span>
</div>
<div>
    <label for="puertos_usados">Puertos Usados</label>
    <span id="puertos_usados" class="inline_blocke values_info">{{values.network_set.all.0.puertos_usados}}</span>
</div>
<div>
    <label for="puerto_switch">Puerto Switch</label>
    <span id="puerto_switch" class="inline_blocke values_info">{{values.network_set.all.0.puerto_switch}}</span>
</div>
<div>
    <label for="cluster">Cluster</label>
    <span id="cluster" class="inline_blocke values_info">{{values.network_set.all.0.cluster}}</span>
</div>
<div>
    <label for="serie_rack">No. Serie</label>
    <span id="serie_rack" class="inline_blocke values_info">{{values.network_set.all.0.serie_rack}}</span>
</div>
<div>
    <label for="no_enclousure">No. Enclousure</label>
    <span id="no_enclousure" class="inline_blocke values_info">{{values.network_set.all.0.no_enclousure}}</span>
</div>
<div>
    <label for="no_serie_oa">No. Serie OA</label>
    <span id="no_serie_oa" class="inline_blocke values_info">{{values.network_set.all.0.no_serie_oa}}</span>
</div>

<div>
    <label for="respaldos">Respaldos</label>
    <span id="respaldos"  class="inline_blocke values_info">{{values.network_set.all.0.respaldos}}</span>
</div> 
<div>
    <label for="monitores">Monitores</label>
    <span id="monitores" class="inline_blocke values_info">{{values.network_set.all.0.monitores}}</span>
</div> 

sitio/templates/pices/details/responsable.html
<div>
    <label for="nombre_aplicacion">Nombre Aplicación</label>
    <span id="nombre_aplicacion"  class="inline_blocke values_info">{{values.responsable_garantia_set.all.0.nombre_aplicacion}}</span>
</div>
<div>
    <label for="empresa">Empresa</label>
    <span  id="empresa" class="inline_blocke values_info">{{values.responsable_garantia_set.all.0.empresa.nombre}}</span>
</div>
<div>
    <label for="responsable">Responsable</label>
    <span id="responsable"  class="inline_blocke values_info">{{values.responsable_garantia_set.all.0.responsable.nombre}}</span>
</div>
<div>
    <label for="area">Area</label>
    <span id="area" class="inline_blocke values_info">{{values.responsable_garantia_set.all.0.area}}</span>
</div>
<h4 class="">GARANTIA</h4>
<div>
    <label for="tipo_soporte">Tipo Soporte</label>
    <span id="tipo_soporte" class="inline_blocke values_info">{{values.responsable_garantia_set.all.0.tipo_soporte}}</span>
</div>
<div>
    <label for="fecha_inicio">Fecha Inicio</label>
    <span id="fecha_inicio"  class="inline_blocke values_info">{{values.responsable_garantia_set.all.0.fecha_inicio}}</span>
</div>
<div>
    <label for="fecha_fin">Fecha Fin</label>
    <span id="fecha_fin" class="inline_blocke values_info">{{values.responsable_garantia_set.all.0.fecha_fin}}</span>
</div>

sitio/templates/pices/details/software.html
<div>
    <label for="osname">Plataforma</label>
    <span id="plataforma" class="inline_blocke values_info">{{values.software_set.all.0.plataforma}}</span>
</div>
<div>
    <label for="publisher">Versión</label>
    <span id="version" class="inline_blocke values_info">{{values.software_set.all.0.version}}</span>
</div>
<div>
    <label for="oscomments">Release</label>
    <span id="release" class="inline_blocke values_info">{{values.software_set.all.0.release}}</span>
</div>
<div>
    <label for="kernell">Service Pack</label>
    <span id="service_pack"  class="inline_blocke values_info">{{values.software_set.all.0.service_pack}}</span>
</div>